import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-around mb-10 md:flex-row">
          <Link href="/">
            <span className="ml-2 text-2xl font-bold">
              Next.js-Tailwind-Test-Task
            </span>
          </Link>
          <Link href="/about-us">
            <span className="ml-2 text-2xl font-bold">About us</span>
          </Link>
          <Link href="/contact-us">
            <span className="ml-2 text-2xl font-bold">Contact us</span>
          </Link>
        </div>

        {children}
      </body>
    </html>
  );
}
